version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  §§INSTANCE-app-db:
    image: mysql:5.7
    container_name: §§INSTANCE-app-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=§§MYSQL_DATABASE_NAME
      - MYSQL_USER=§§MYSQL_DATABASE_USER
      - MYSQL_PASSWORD=§§MYSQL_DATABASE_PASSWORD
    volumes_from: 
      - §§INSTANCE-app-data
    depends_on:
      - §§INSTANCE-app-data


#  §§INSTANCE-adminer:
   image: adminer
   container_name: §§INSTANCE-app-adminer
   restart: unless-stopped
   networks:
      - bibbox-default-network
   links:
      - §§INSTANCE-app-db:app-db
    ports:
      - "§§PORT1:80"
    depends_on:
      - §§INSTANCE-app-db
      - §§INSTANCE-app-data
    volumes_from: 
      - §§INSTANCE-app-data

  §§INSTANCE-app-data:
    image: busybox
    container_name: §§INSTANCE-app-data
    volumes:
      - ./data/app-data:/var/lib/mysql

